spring:
  application:
    name: spb3email
  mail:
    host: smtp.gmail.com
    port: 587
    username: oat431
    password: xxxxxxxxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
